### ISSUE TITLE
User is never notified if request has expired and auto garbage collection is enabled

### ISSUE THREAD

**Issue by kbond** [SymfonyCasts/reset-password-bundle#100]
Automatic garbage collection occurs before fetching the request in `ResetPasswordHelper::validateTokenAndFetchUser()`. Expired requests are removed before being fetched. They never get checked to see if they are expired so a `ExpiredResetPasswordTokenException` will never be thrown.

I thought about doing the garbage collection after (like in `try...finally`) but it still doesn't fully fix the issue as garbage collection happens on generating and fetching. On a busy site, expired tokens would be cleaned up quickly.

One solution is to make the garbage collection time configurable.

WDYT?

**Comment by kbond** [comment]
Another solution is to customize the `removeExpiredResetPasswordRequests` repo method in your app:

```php
public function removeExpiredResetPasswordRequests(): int
{
    $time = new \DateTimeImmutable('-1 week'); // this is the change
    $query = $this->createQueryBuilder('t')
        ->delete()
        ->where('t.expiresAt <= :time')
        ->setParameter('time', $time)
        ->getQuery()
    ;

    return $query->execute();
}
```

Maybe this should be the default?

**Comment by weaverryan** [comment]
I was thinking the same thing: it effectively gets fixed pretty easily if you keep tokens for a week or so after. I don't see any disadvantage to this - we should do it :)

**Comment by kbond** [comment]
I'll open a PR
