### ISSUE TITLE
Add getMessageKey()/getMessageData() to ResetPasswordExceptionInterface

### ISSUE THREAD

**Issue by kbond** [SymfonyCasts/reset-password-bundle#102]
Symfony's `AuthenticationException` has this to help with translation.

**Comment by weaverryan** [comment]
Yo Kevin!

Hmm, I see yes. So the `getReason()` is already equivalent (I think) to `getMessageKey()`: both are basically hardcoded & safe "error strings". Unless you disagree, it means that we're just missing the `getMessageData()` method, which would give you access, for example, to the (for example) retry timeout in `TooManyPasswordRequestsException`. So, for that exception, it would look something like this:

```php
public function getReasonData()
{
    return ['{{ retry_time }}' => $this->retryTime];
}
```

(btw, not sure on the naming there - should that exception give you the overall retry TTL? Or how much time is *actually* left until this one user can retry? And should it be in seconds, minutes? I don't think we can push a DateTime object into this, right?

Thanks!

**Comment by kbond** [comment]
> So the `getReason()` is already equivalent (I think) to `getMessageKey()`

Ok, as long as it's understood that changing the `getReason()` text will be considered a BC break as it will break translation keys.

> I don't think we can push a DateTime object into this, right?

I think the `TooManyPasswordRequestsException` should have a method that returns a `DateTime` object as to when it can be next retried and let the user determine how to use. We can discuss further in #101 

> it means that we're just missing the `getMessageData()`

I don't know if this is strictly necessary (and adding to the interface would be a BC break, correct?). Depending on how we handle the "retry after" for `TooManyPasswordRequestsException` it might not be feasible to put here...

**Comment by weaverryan** [comment]
> Ok, as long as it's understood that changing the getReason() text will be considered a BC break as it will break translation keys.

Very good point. Yes, we will follow this 👍 

I'm going to close for now, since we solved the specific problem with `TooManyPasswordRequestsException`.
