### ISSUE TITLE
POST Request for password reset

### ISSUE THREAD

**Issue by JValentas** [SymfonyCasts/reset-password-bundle#107]
Hello,

Is there any way to make a POST call with some parameters like email address for password reset request or you must use the generated web template?
For example to make a request call from mobile app, instead of opening browser.

Thanks for the replies in advance.

**Comment by kbond** [comment]
Not out of the box with the provided controller trait or generated maker bundle code. You would have to write custom controller(s). Everything else from this bundle could still be used though.

**Comment by weaverryan** [comment]
That's exactly the idea :). The bundle gives you all the tools to do this - you'll just need to implement the route & controller yourself. I would be happy to have a simple example in the docs if someone wants to contribute it :).

**Comment by kbond** [comment]
Might be an idea for a 2.0 release: a non-session based controller trait/helper.

**Comment by jrushlow** [comment]
Added a note of this issue on the future board. I like @weaverryan idea of an example added into the docs. 

After I get the verify bundle up to speed, I’ll take a stab at some sort of native support for POST / alternative API requests if someone doesn’t beat me to it. My knee jerk reaction is to say that it would be pretty similar to the existing helper class, so I’m not sure as to how much value that would add to the bundle.

**Comment by fd6130** [comment]
Do we have anything need to take note if we use this bundle and modify it to use REST instead of twig? 

Since the token will be save in session when using Form, how about REST?

**Comment by jrushlow** [comment]
I'm going to close this for now as it is related to #128. We should have a solution in our docs & a PR up in MakerBundle later today that explains / provides a implementation for API based resets.
