### ISSUE TITLE
make: reset-password ne ma pas crée ChangePasswordFormType.php

### ISSUE THREAD

**Issue by Tritaniumm** [SymfonyCasts/reset-password-bundle#112]
Bonjour,

J'ai le soucie comme dit dans le titre mais je ne trouve vraiment 0 réponse sur les docs ou bien même sur google .

Voila se que j'aurai du avoir :
...
php bin/console make:reset-password

created: src/Controller/ResetPasswordController.php
created: src/Entity/ResetPasswordRequest.php
created: src/Repository/ResetPasswordRequestRepository.php
updated: config/packages/reset_password.yaml
created: src/Form/ResetPasswordRequestFormType.php
created: src/Form/ChangePasswordFormType.php
created: templates/reset_password/check_email.html.twig
created: templates/reset_password/email.html.twig
created: templates/reset_password/request.html.twig
created: templates/reset_password/reset.html.twig
...

et Voila se que j'ai :
....
created: src/Controller/ResetPasswordController.php
created: src/Entity/ResetPasswordRequest.php
created: src/Repository/ResetPasswordRequestRepository.php
updated: config/packages/reset_password.yaml
created: src/Form/ResetPasswordRequestFormType.php
...
Voila voila .. merci d'avance pour vos future réponce !

**Comment by jrushlow** [comment]
Good morning, Did `src/Form/ChangePasswordFormType.php` already exist in the project before running `make:reset-password?

**Comment by Tritaniumm** [comment]
No, I don't really understand this problem

**Comment by jrushlow** [comment]
Hmmm interesting. What version of `PHP`, `Symfony`, And  `symfony/maker-bundle`  you using? I’m not in front of my computer right now, but later tonight I’ll investigate further.

Any other details about your development environment may be helpful as well.

**Comment by jrushlow** [comment]
I'm unable to reproduce the scenario locally. 

```
developer@8d5bc65d9681:/var/develop/test-rp-mkr-bug$ bin/console make:reset-password

Let's make a password reset feature!
====================================

 Implementing reset password for App\Entity\User

- ResetPasswordController -
---------------------------

 A named route is used for redirecting after a successful reset. Even a route that does not exist yet can be used here.

 What route should users be redirected to after their password has been successfully reset? [app_home]:
 > 

- Email -
---------

 These are used to generate the email code. Don't worry, you can change them in the code later!

 What email address will be used to send reset confirmations? e.g. mailer@your-domain.com:
 > jr@rushlow.dev

 What "name" should be associated with that email address? e.g. "Acme Mail Bot":
 > SymfonyCasts

 created: src/Controller/ResetPasswordController.php
 created: src/Entity/ResetPasswordRequest.php
 created: src/Repository/ResetPasswordRequestRepository.php
 updated: config/packages/reset_password.yaml
 created: src/Form/ResetPasswordRequestFormType.php
 created: src/Form/ChangePasswordFormType.php
 created: templates/reset_password/check_email.html.twig
 created: templates/reset_password/email.html.twig
 created: templates/reset_password/request.html.twig
 created: templates/reset_password/reset.html.twig
           
  Success! 
           
 Next:
   1) Run "php bin/console make:migration" to generate a migration for the new "App\Entity\ResetPasswordRequest" entity.
   2) Review forms in "src/Form" to customize validation and labels.
   3) Review and customize the templates in `templates/reset_password`.
   4) Make sure your MAILER_DSN env var has the correct settings.
   5) Create a "forgot your password link" to the app_forgot_password_request route on your login form.

 Then open your browser, go to "/reset-password" and enjoy!

developer@8d5bc65d9681:/var/develop/test-rp-mkr-bug$ 
```

To confirm you are just seeing -
```
created: src/Controller/ResetPasswordController.php
 created: src/Entity/ResetPasswordRequest.php
 created: src/Repository/ResetPasswordRequestRepository.php
 updated: config/packages/reset_password.yaml
 created: src/Form/ResetPasswordRequestFormType.php

  Success! 
           
 Next:
   1) Run "php bin/console make:migration" to generate a migration for the new "App\Entity\ResetPasswordRequest" entity.
   2) Review forms in "src/Form" to customize validation and labels.
   3) Review and customize the templates in `templates/reset_password`.
   4) Make sure your MAILER_DSN env var has the correct settings.
   5) Create a "forgot your password link" to the app_forgot_password_request route on your login form.

 Then open your browser, go to "/reset-password" and enjoy!
```

What is the name of the property in the users entity and associated getter method name? e.g. `User::email` & `User::getEmail()`

**Comment by Tritaniumm** [comment]
on a forum I was told to delete all the files created then started again, probably a little bug


i'm sorry if my english is bad, i use google translation

**Comment by jrushlow** [comment]
Is it working correctly now?

**Comment by Tritaniumm** [comment]
YEEEEEES ^^' 


3 days that I try to find a solution ...
Just delete all the files related to symfonycasts / reset-password-bundle
and to start again

**Comment by jrushlow** [comment]
I'm glad everything is working. If there is anything else you need help with, please let us know! Thank you for using Reset Password Bundle!
