### ISSUE TITLE
Modify the error messages

### ISSUE THREAD

**Issue by dd2424** [SymfonyCasts/reset-password-bundle#113]
Hello, how to modify the error messages? Some are not in the controller. thank you.

**Comment by jrushlow** [comment]
The bundle generates exceptions that can be caught with -

```
try {
   xyz...
} catch (SymfonyCasts\Bundle\ResetPassword\Exception\ResetPasswordExceptionInterface $ex) { 
    $message = $ex->getReason();
    ...
}
```

After catching the exception (if one is thrown) you can pass the `$message` onto your templates or disregard it and create your own for use in the templates. The `make:reset-password` command generates `flash` messages which can be customized or removed in the generated `ResetPasswordController`.

- [PHP Exception Handling](https://www.php.net/manual/en/language.exceptions.php)
- [Symfony Flash Messages](https://symfony.com/doc/current/controller.html#flash-messages)

I hope this helps, feel free to provide an example message that you would like to change - I would be more than happy to give an example of how this can be done in the controller.
