### ISSUE TITLE
Idea to make a more generic bundle

### ISSUE THREAD

**Issue by bashilbers** [SymfonyCasts/reset-password-bundle#116]
Hey!

I really like this bundle but I also need secure token generation for a) confirming a registration and b) changing a email. Both require a similar structure as used in this bundle. Do you think it would be cool to have some "user-token" bundle as dependency on this bundle? So we can easily scaffold other systems that require confirmation tokens?

**Comment by jrushlow** [comment]
Howdy & thank you for using the bundle! For email verification we actually have the [VerifyEmailBundle](https://github.com/SymfonyCasts/verify-email-bundle) that was just released. Please note that the associated maker command, `make:registration-form`, has an update that has not yet been merged into Symfony's Maker Bundle. Hopefully we will make that happen this week. 

For email changes, the `VerifyEmailBundle` would again be your best friend! The readme demonstrates how to use the bundle without the maker command, but with a little tweaking, it should give you an idea of how to use the bundle for email address changes as well.
