### ISSUE TITLE
 Command "make:reset-password" is not defined.

### ISSUE THREAD

**Issue by azarual** [SymfonyCasts/reset-password-bundle#118]
Hi there the command is not found
 Command "make:reset-password" is not defined.

**Comment by jrushlow** [comment]
What version is shown when you run `composer show symfony/maker-bundle` ? It should be one of the first lines printed following that command. To use the `make:reset-password` command, you need `symfony/maker-bundle` `v1.15.0` or greater.

**Comment by nguyenductien1** [comment]
Hi, I have same problem with versions v1.34.1
