### ISSUE TITLE
ResetPasswordRequestInterface

### ISSUE THREAD

**Issue by mysiar** [SymfonyCasts/reset-password-bundle#127]
should this method return object or Symfony\Component\Security\Core\User\UserInterface

public function getUser(): object;

**Comment by weaverryan** [comment]
Hi @mysiar!

In practice, it will return a `UserInterface`. But as far as this bundle is concerned, you could return *any* object from this method. Or, to say it a different way, there is nowhere in this bundle that actually cares/uses what you return from here (unless you're opting into the optional, entity integration). And so, we chose to not enforce `UserInterface`, which is technically not required by the bundle.

Cheers!

**Comment by Yopai** [comment]
In the code generated by the maker, it is used in encodePassword.
So it would be meaningful to type-hint (at least in phpdoc) it as UserInterface.
