### ISSUE TITLE
Password reset fails on non confirmed accounts

### ISSUE THREAD

**Issue by sjobke** [SymfonyCasts/reset-password-bundle#132]
When people register and fail to confirm their account, password reset also fails.
Any ideas on how to fix this issue?

**Comment by weaverryan** [comment]
Hey @sjobke!

Hmm. Can you tell us a bit more? I would think these would be independent of each other, but I could be wrong (that happens a lot ;) ). What behavior are you seeing?

Cheers!

**Comment by sjobke** [comment]
Imagine this journey. You create an account, you fail to receive the confirmation e-mail. Then you try to restore your password, but that does not work for unconfirmed accounts. Registering again  is not possible as email is already in use.

**Comment by jrushlow** [comment]
Are you using the `syfomycasts/verify-email-bundle` for email verifications?

In general, reset password doesn't care if an account if verified or not. However, it is possible code else is preventing verification from happening.

**Comment by jrushlow** [comment]
@sjobke I'm going to close this issue for now as I don't believe the cause is directly related to `ResetPasswordBundle`. Feel free to reopen if you're still reexperience issues. Thanks!
