### ISSUE TITLE
reset_password.yaml is not created

### ISSUE THREAD

**Issue by Nebja** [SymfonyCasts/reset-password-bundle#133]
Hello , 

I installed the package , and it worked fine but i had to roll back for some reason and now it doesnt create reset_password.yaml (_We can't find config/packages/reset_password.yaml. That's ok, you probably have a customized configuration._) and then 

`Cannot autowire service "App\Controller\ResetPasswordController": argument "$resetPasswordHelper" of method "__construct()" references interface "SymfonyCasts\Bundle\ResetPassword\ResetPasswordHelperInterface" but no such service exists. Did you create a class that implements this interface?`

When i create the yaml file alone with this code :

`symfonycasts_reset_password:
  request_password_repository: App\Repository\PasswordResetRequestRepository
  lifetime: 3600
  throttle_limit: 3600
  enable_garbage_collection: true`

I get : 

`There is no extension able to load the configuration for "symfonycasts_reset_password" (in "C:\wamp64\www\mysite\symfony\config/packages/reset_password.yaml"). Looked for namespace "symfonycasts_reset_password", found ""framework", "twig", "twig_extra", "maker", "doctrine", "doctrine_migrations", "security", "sensio_framework_extra", "symfonycasts_verify_email", "web_profiler", "monolog", "debug", "knpu_oauth2_client", "vich_uploader", "ch_cookie_consent", "stof_doctrine_extensions"" in C:\wamp64\www\mysite\symfony\config/packages/reset_password.yaml (which is loaded in resource "C:\wamp64\www\mysite\symfony\config/packages/reset_password.yaml").`

I am new to this , so if it is a stupid question , i am sorry in advance . 
Thanks for your time .

**Comment by weaverryan** [comment]
Hey @Nebja!

No worries :). It looks like you installed the bundle, but removed its config... but then when you reinstalled it, for some reason the recipe system doesn't want to re-install the recipe for you. I think you added the correct config, but I have a feeling that the bundle is also not be re-enabled (usually a job of the recipe system). Let's just force the recipe to be re-installed. Run this from the command line:

```
composer recipes:install symfonycasts/reset-password-bundle --force -v
```

That should re-enable the bundle and give you a good config file (which you can then customize). If you continue having any issues, let us know.

Cheers!

**Comment by vincentcox** [comment]
@weaverryan : this gives the following error:

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "recipes" namespace.
```

**Comment by jrushlow** [comment]
This maybe related to an undetermined issue with Symfony recipe's see #159

**Comment by weaverryan** [comment]
Hey @vincentcox!

> @weaverryan : this gives the following error:

Check `composer show symfony/flex` - the `recipes:install` command was added in 1.6.0 (which is pretty old - so if you are on an older version, definitely upgrade to the latest).

Cheers!

**Comment by vincentcox** [comment]
Hey @weaverryan !

I am using a recent version of composer (the 2.x):

![image](https://user-images.githubusercontent.com/9286611/109990521-c0ef0680-7d09-11eb-94af-8b8256a066be.png)


So I assume that I should install Symfony flex? 

Will it impact my existing project if I install flex?

**Comment by vincentcox** [comment]
It's fixed with `composer require symfony/flex`and now it works properly!

**Comment by jrushlow** [comment]
For future reference, for projects that are not able to use Symfony Flex, manually creating the required configuration file can be done as described -> https://github.com/SymfonyCasts/reset-password-bundle#configuration

More information on Symfony Flex can be found -> https://symfony.com/doc/current/setup/flex.html & https://flex.symfony.com/
