### ISSUE TITLE
ResetPasswordController doesn't call setPassword

### ISSUE THREAD

**Issue by sdespont** [SymfonyCasts/reset-password-bundle#136]
After using `bin/console make:reset-password`, the generated `ResetPasswordController`.php class doesn't set the reseted password because `getPassword` is called instead of `setPassword`. Or am I missing something?

    public function reset(Request $request, UserPasswordEncoderInterface $passwordEncoder, string $token = null): Response
    {
        ........

        if ($form->isSubmitted() && $form->isValid()) {
            // A password reset token should be used only once, remove it.
            $this->resetPasswordHelper->removeResetRequest($token);
            
            // Encode the plain password, and set it.
            $encodedPassword = $passwordEncoder->encodePassword(
                $user,
                $form->get('plainPassword')->getData()
            );

            // =======> SHOULD BE setPassword <<======
            $user->getPassword($encodedPassword);

            $this->getDoctrine()->getManager()->flush();

            // The session is cleaned up after the password has been changed.
            $this->cleanSessionAfterReset();

            return $this->redirectToRoute('navigation_home');
        }

        return $this->render('User/User/reset_password/reset.html.twig', [
            'resetForm' => $form->createView(),
        ]);
    }

**Comment by jrushlow** [comment]
Hi @sdespont, does your user entity have a setPassword() method and did maker ask you to provide the name of the method to set the password?

**Comment by sdespont** [comment]
@jrushlow Thanks for your reply. Yes, my user entity has the setPassword() method. In fact, I am impleting the `reset-password-bundle` right now. Therefore, I didn't test, but I don't understand how it could work without setting the new encoded password.

**Comment by weaverryan** [comment]
Hey @sdespont!

Here is the template in MakerBundle that generates the line of code in question: https://github.com/symfony/maker-bundle/blob/0f1d3ed2584349dc8700d7908e8a92b3742b1c99/src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php#L138

As you can see, it's dynamic, using the `$password_setter` variable, which ultimately comes from this: https://github.com/symfony/maker-bundle/blob/main/src/Security/InteractiveSecurityHelper.php#L207-L217

That method either returns `setPassword()` or, if it doesn't find one, it should ask you which public method to use. Do you remember what this step looked like when you used `make:reset-password`? My guess (but there could be a bug) is that it asked you which method to use and you entered `getPassword()`. But... it should have only asked you this question if your `User` did *not* have a `setPassword()` method. Does your `User` class have a `setPassword()` method?

**Comment by sdespont** [comment]
Thank you for your time. When I ran `make:reset-password`, my `User `entity didn't have `setPassword`. So, your guess is probably right and I made a typo.
