### ISSUE TITLE
Incorrect expiry date when using release 1.2.1 and database is in different timezone

### ISSUE THREAD

**Issue by Jontsa** [SymfonyCasts/reset-password-bundle#138]
Not sure if this is a bug or a feature but release 1.2.1 with PR #135 changed how the token expiry date is created and this resulted in unexpected behaviour when database (MySQL) is in different timezone than your application.

For example in my dev environment, the database uses UTC timezone but my PHP application is in +02:00. When password reset request is created using 1.2.0, the `expiresAt` DateTimeImmutable uses timezone +02:00. So for example expiration time of 09:00:00+02:00 is stored as 09:00:00 in MySQL DATETIME and when it is read from database, it becomes 09:00:00+02:00.

After upgrading to 1.2.1, the expiration DateTimeImmutable is set to timezone +00:00 [here](https://github.com/SymfonyCasts/reset-password-bundle/pull/135/files#diff-25523e47f917ef508819743ff1c28ea32f2651f3884fe0110402b26ee4d129dfR75). So now expiresAt is 07:00:00+00:00 and is stored as 07:00:00 in MySQL DATETIME. When password reset request is then read from database, the `expiresAt` becomes 07:00:00+02:00 because there is no timezone information attached and ResetPasswordRequestTrait::isExpired() will return false.

Easy fix for me is to set my dev environment to use UTC also but maybe this is not possible for everyone.

**Comment by jrushlow** [comment]
thanks @Jontsa for the heads up! I've created a fix and we should have it pushed out shortly.

**Comment by weaverryan** [comment]
Tagged! It should be fixed now, but please @Jontsa if you still notice any issues, let us know. Thank you for the very clear bug report!
