### ISSUE TITLE
Wrong expiry time in templates/reset_password/check_email.html.twig

### ISSUE THREAD

**Issue by MartenTacoma** [SymfonyCasts/reset-password-bundle#146]
With the default settings the email sent page gives a different expire than the mail. I confirmed in the database that the mail is right and the page is wrong. The cause is that the page uses date('g') which is timezone dependent. So a value of 3600 will indeed give 1 hour when timezone is UTC, but for CET (UTC+1) it will return 2. My fix is to replace `{{ tokenLifeTime|date('g') }}` with `{{ tokenLifeTime/3600 }}`.

**Comment by weaverryan** [comment]
Hey @MartenTacoma!

Thanks for using the bundle :). What version are you on? This could be related to #142 or #119

Cheers!

**Comment by jrushlow** [comment]
Howdy @MartenTacoma - have a look at #142, I believe this should resolve your issue if your dependencies are up to date. Run `composer outdated` to see if either `symfonycasts/reset-password-bundle` or `symfony/maker-bundle` are outdated. `reset-password-bundle` should be at least `v1.3.0`. If they're outdated, a quick `composer update` will get your dependencies in the right spot.

I've added an item to my todo list to update https://github.com/SymfonyCasts/reset-password-bundle/blob/master/docs/manual-setup.md which will include examples of what the latest and greatest implementation of `reset-password-bundle` should look like in a Symfony application. 

If you get stuck, feel free to reach out for help - we'll get you back on track...

**Comment by jrushlow** [comment]
I'm going to close this for now as I believe this issue has been addressed in recent releases. @MartenTacoma if you are still having problems, feel free to reach out to use and we'll be happy to help! thank you!
