### ISSUE TITLE
Consider undeprecating canCheckEmail / setCanCheckEmailInSession

### ISSUE THREAD

**Issue by jellynoone** [SymfonyCasts/reset-password-bundle#154]
I used the maker command to generate the initial code then made heavy customizations after I figured how everything worked. I recently update the bundle and saw that the canCheckEmail / setCanCheckEmailInSession are deprecated.

I understand the reasoning behind this, but I cannot find a way to actually send a user that entered a non-existing email to the next part of the authentication process.

The bundle suggest that instead of using the deprecated methods we should set the token, but we cannot set the token unless the user actually exists. So if we follow the bundle and the generated code strictly we now expose whether the user exists or not, or have to write the same functionality the bundle is deprecating.

I think this is not an issue for the maker bundle.

**Comment by jrushlow** [comment]
Howdy @jellynoone - I do not foresee us removing the deprecation's for those methods. The referenced issues should solve the problem. I've also posted a temporary solution in https://github.com/symfony/maker-bundle/issues/808 until a final implementation can be released. Thanks!
