### ISSUE TITLE
There is no extension able to load the configuration for "symfonycasts_reset_password"

### ISSUE THREAD

**Issue by vincentcox** [SymfonyCasts/reset-password-bundle#159]
Hello there,

First of all thanks for making this bundle! Unfortunately I got some troubles installing it.

I followed the documentation and used the command from the readme:

```bash
bin/console make:reset-password
```
So it gives me a succesful installation:

![image](https://user-images.githubusercontent.com/9286611/109861231-5bded680-7c5f-11eb-8403-b9c3990448ba.png)

However if I access a page or try the `php bin/console make:migration` command, I get the following error in both cases:

`
There is no extension able to load the configuration for "symfonycasts_reset_password" (in "<...>/config/packages/reset_password.yaml"). Looked for namespace "symfonycasts_reset_password", found ""framework", "twig", <...>".
`

I tried the following command I found somewhere in the issues for someone with a similar situation:
```bash
composer recipes:install symfonycasts/reset-password-bundle --force -v
```

Unfortunately this gives me:

`  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "recipes" namespace.`

My versions:
- Composer: `Composer version 2.0.11 2021-02-24 14:57:23`, also tried the 1.X version but same results
- Symfony: 5.2.1

Any ideas what is going wrong? Thanks in advance.

**Comment by vincentcox** [comment]
Sorry, forgot to link to the related issue but it seems that you re-opened https://github.com/SymfonyCasts/reset-password-bundle/issues/133 already.

**Comment by jrushlow** [comment]
Hi @vincentcox thanks for bringing this to our attention. I do not think this is related to the bundle itself but an issue with Symfony's recipe's. I'll look into this tomorrow morning and see if I can figure out what is happening.

This appears to be related to #133

**Comment by vincentcox** [comment]
If I can provide any more info on my end, please let me know! Thanks and good luck!

**Comment by vincentcox** [comment]
Hi @jrushlow,

It seems that running `composer require symfony/flex` fixed the installation process and now I got the project up and running. You might close this duplicate issue and possibly also the linked original issue. Thanks for the help and have a nice day!

**Comment by jrushlow** [comment]
Awesome, that's great to hear @vincentcox

For future reference, for projects that are not able to use Symfony Flex, manually creating the required configuration file can be done as described -> https://github.com/SymfonyCasts/reset-password-bundle#configuration
