### ISSUE TITLE
Delete Cascade

### ISSUE THREAD

**Issue by victor-paumier** [SymfonyCasts/reset-password-bundle#172]
Hi,

I just encountered a case where a user tried to delete their account right after making a password reset request, which resulted in an error due to the absence of the onDelete="CASCADE" statement.
Is this voluntary or is it because maker bundle does not allow to generate this statement?

Thank you!

**Comment by jrushlow** [comment]
Howdy @victor-paumier - Thanks for the question, I'm moving this over to `symfony/maker-bundle` as this issue is related to the `make:reset-password` command which generates the `ResetPasswordRequest` entity

**Comment by dt-justin** [comment]
Is there an example of how to manually fix this issue?  This is very old and the resulting ticket has no replies at all.  I've tried to add a cascade to it but migration doesn't remove and re add the constraint.

**Comment by dt-justin** [comment]
I figured it out.  Thanks

for others looking, this is on Symfony 7.3

in `App\Entity\User` add

```
#[ORM\OneToMany(targetEntity: ResetPasswordRequest::class, mappedBy: 'user', cascade: ['remove'])]
private $resetPasswordRequests;
```

in `App\Entity\ResetPasswordRequest` change `#[ORM\ManyToOne]` to

```
#[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'resetPasswordRequests')]
```

and that's it.

**Comment by weaverryan** [comment]
Thanks 💯 for sharing @dt-justin!
