### ISSUE TITLE
Missing symfony/form requirement

### ISSUE THREAD

**Issue by apphancer** [SymfonyCasts/reset-password-bundle#173]
When running `make:reset-password` there should be a missing package error if the following are missing:

- symfony/form
- symfony/validator

At the moment, if symfony/mailer is not available, the `make:reset-password` command returns this as error suggesting to run ` composer require symfony/mailer`.
It would be helpful if the same happened for `symfony/form`.

**Comment by jrushlow** [comment]
Howdy @apphancer Thanks for the feedback - I've moved this over to `symfony/maker-bundle` as this is directly related to the `make:reset-password` command
