### ISSUE TITLE
Multiple password reset tokens

### ISSUE THREAD

**Issue by kbond** [SymfonyCasts/reset-password-bundle#18]
One thing I noticed in the make-bundle implementation, is it wasn't possible to re-request a reset if there was a valid token available. This is important if sending the email fails. I believe this bundle allows for this with the request throttle time, but I just wanted to confirm.

**Comment by jrushlow** [comment]
In it's current form, the reset bundle has 2 configurable parameters in regards to a request's life span:

`lifetime` : The length of time a reset token is valid after it has been created.
`throttle_limit`: Another password reset cannot be made faster than this throttle time in seconds.

The way things are working now, a user would not be able to request another reset if a valid request exists, & any subsequent request's were made before the throttle limit. This prevents a bad actor from hammering away requesting reset after reset.

So the short answer to your question, is no. At least not as things stand at the moment. But, we're still molding this bundle, and it's maker-bundle counterpart (templates for controllers, repositories, etc...), so some mechanism for re-sending the email may become apart of the initial release.

**Comment by kbond** [comment]
Right, if I set the `lifetime` to 1 hour and the `throttle_limit` to 5 minutes, then after 5 minutes, the user would be able to request another reset? Then there would be 2 valid tokens for a time (55 minutes)?

**Comment by jrushlow** [comment]
Correct-ish.. hehe

> Right, if I set the lifetime to 1 hour and the throttle_limit to 5 minutes, then after 5 minutes, the user would be able to request another reset?

Yes

> Then there would be 2 valid tokens for a time (55 minutes)?

Technically, yes. However, the logic for retrieving a reset request from persistence, only looks for the newest request. So in your example, the first request would still be valid from a lifetime perspective, but it wouldn't be able to be used if subsequent valid requests exist.

**Comment by kbond** [comment]
I mention this because I have experienced the scenario where a user requests a reset, the email is delayed, so they request another, this second email is also delayed but they receive the first. When they click the link, it is no longer valid causing frustration and another round or reset, waiting, clicking an invalid link...

I think this should be addressed because this is what a separate db table for resets allows us to avoid.

**Comment by kbond** [comment]
> However, the logic for retrieving a reset request from persistence, only looks for the newest request. So in your example, the first request would still be valid from a lifetime perspective, but it wouldn't be able to be used if subsequent valid requests exist.

I'm looking at [the code here](https://github.com/SymfonyCasts/reset-password-bundle/blob/841890d6bc9a0f87af06c40384096618378d776b/src/ResetPasswordHelper.php#L95) and it looks like it doesn't get the newest request but just any token that matches. I could be mistaken but I think both tokens would work.

**Comment by jrushlow** [comment]
Scratch that, you're correct. I was confusing the generation and validation. When generating a token the bundle looks up the most recent reset request from persistence to enforce throttling. But during validation, it grabs a request by the selector and then checks if it is expired.

**Comment by kbond** [comment]
Ok, perfect, I guess my only suggestion would be if you do change the default behaviour to look at only the most recent token, we have an option to change.

I think though, having the `lifetime` and `throttle_limit` the same (the default right now) or different, enables/disables this.

Bottom line, all looks good as is, I'm excited to use this bundle!
