### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by saul-lopez** [SymfonyCasts/reset-password-bundle#182]
Hi.. 

I'm trying to use the reset-password-bundle with a PostgreSQL database. 

The generated entity `ResetPasswordRequest` has this property:

```php
/**
 * @ORM\ManyToOne(targetEntity=User::class)
 * @ORM\JoinColumn(nullable=false)
 */
private $user;
```

However, `user` is a PostgreSQL reserved word and this creates some problems with the bundle.

I found that using the  annotation ` @Column(name="`user`")` helps: I can fill the reset password form with an email address and the email is sent correctly,  but when i access the link provided in the email I get an error in the browser:

```
Return value of App\Entity\ResetPasswordRequest::getUser() must be an object, int returned
```
I think its related to this fact:

> Doctrine will then quote this column name in all SQL statements according to the used database platform.
>
>Identifier Quoting does not work for join column names or discriminator column names unless you are using a custom >QuoteStrategy.
[Quoting reserved words](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words)

The question is, can I, in some way, change the attribute name so that it isn't a Postgres reserver word or what can I do?

Thanks.

**Comment by jrushlow** [comment]
Howdy @saul-lopez - does your user entity have a table name attribute? e.g. 

```php
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
}
```

I have this implemented in an app the uses postgres and using the reserved `user` and have not run into any issues.

Hope this helps!
