### ISSUE TITLE
Require reset-password-bundle error

### ISSUE THREAD

**Issue by nguyenductien1** [SymfonyCasts/reset-password-bundle#191]
Hi, I'm using versions v1.34.1 of  symfony/maker-bundle, when I use command: composer symfonycasts/reset-passwords-bundle, It returned:  
[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "symfonycasts/reset-password-bundle" is not defined.

**Comment by jrushlow** [comment]
Howdy @nguyenductien1 try `composer require symfonycasts/reset-password-bundle` and then run `make:reset-password`.
