### ISSUE TITLE
The Bundle is removed when installe anotherone

### ISSUE THREAD

**Issue by AntonioMorenoPC** [SymfonyCasts/reset-password-bundle#197]
Hello, Why when I try to install another bundle , resest-password is uninstalled? reset_password.yaml is removed, composer.json references to reset-pasword removed as well, symfony.lock...

**Comment by jrushlow** [comment]
This might be related to issue #179 .

- Which bundle is causing `reset-password-bundle` to be uninstalled?
- What is the full output of `composer` when this happens?

**Comment by AntonioMorenoPC** [comment]
Thanks for your answer, 
I've solved the problem as #179 issue. 
Upgrade composer.
install the bundles (event-dispatcher, telegram-notifier..) that happened with all the bundles I've tried.
And finally install reset-password. 
Regards.
