### ISSUE TITLE
Translation reason

### ISSUE THREAD

**Issue by gunter423** [SymfonyCasts/reset-password-bundle#202]
Hi, 

I have a question, there are possibility to translate the reason that return for exceptions :

ResetPasswordExceptionInterface
ExpiredResetPasswordTokenException
FakeRepositoryException
InvalidResetPasswordTokenException
TooManyPasswordRequestsException 

? :)

**Comment by Snowbaha** [comment]
Hello, I Was asking myself the same thing. Is it not possible or just no time to do it?

**Comment by gunter423** [comment]
> Hello, I Was asking myself the same thing. Is it not possible or just no time to do it?

It's not possible :'(

**Comment by AxelBriche** [comment]
Up, class has "final" prefix and cannot be overwrited.
Can you please add some translations for that messages?

**Comment by bocharsky-bw** [comment]
Hey guys! You're correct, it's not translated out of the box (yet) unfortunately - I'll try to think about it. But, you don't need to be able to override that exception class to translate the message - just leverage the Symfony Translator component. Let me give you a workaround.

First of all, thanks to Maker bundle that generated the actual code in _your_ code base - you can easily tweak it if you need. Open your `ResetPasswordController::reset()`, then inject there Symfony Translator object and wrap the actual message with `trans()`:
```php
public function reset(TranslatorInterface $translator, Request $request, UserPasswordHasherInterface $passwordHasher, string $token = null): Response
{
    // ...
    try {
        // ...
    } catch (ResetPasswordExceptionInterface $e) {
        $this->addFlash('reset_password_error', $translator->trans(sprintf(
            'There was a problem validating your reset request - %s',
            $e->getReason()
        )));

        // ...
    }
}
```

That's it! That's literally the only workaround you need. Finally, all you need to do is actually translate those complete messages in your translation files, e.g. in my `messages.uk.yml` I wrote:
```yaml
# ...
"There was a problem validating your reset request - The reset password link is invalid. Please try to reset your password again.": Виникла проблема під час перевірки вашого запиту на скидання – посилання для скидання пароля недійсне. Спробуйте скинути пароль ще раз.
```

And so on for other ResetPasswordExceptionInterface possible exception messages, don't forget to prefix all of them with `There was a problem validating your reset request - ` as you see from the controller :)

I just double-checked it in my project - it works for me:
<img width="559" alt="Screenshot 2022-01-28 at 10 57 23" src="https://user-images.githubusercontent.com/3317635/151517143-1f50d888-9e5c-4f64-8d2f-1bc6b57e0ed0.png">

**Comment by gunter423** [comment]
Thanks @bocharsky-bw
