### ISSUE TITLE
using Reset Password for multiple users / firewalls

### ISSUE THREAD

**Issue by Hanmac** [SymfonyCasts/reset-password-bundle#203]
assuming i have a backend user bundle that uses this password reset bundle.

then i want to use a different kind of user bundle for the frontend users which might also use this bundle for password reset.

i assume they might conflict depending on the implementation of the request repository?

would i need a delegator repository depending on the class of user?

**Comment by jrushlow** [comment]
Howdy @Hanmac - yes, the bundle as is does not support multiple user entities out of the box. checkout #110 for a few work arounds until we properly implement multi entity support.

I'm going to close this for now, but if #110 doesn't cover what you're looking for, please let me know and ill open this back up. Thanks for using the bundle!

**Comment by Hanmac** [comment]
i think it is going to depend if I'm going to use the SonataUserBundle or the NucleosUserAdminBundle for the final product in Backend. Because that's the difference if I'm going to need an extra User for Frontend or not.

One of the requirements is that my Frontend users need to be able to share the same e-mail if able. It is a software for a school where the students need to register, and siblings might have the same e-mail.

From what i have seen with this bundle, it shouldn't be that much of a Problem.
