### ISSUE TITLE
Parameter enable_garbage_collection doesn't work 

### ISSUE THREAD

**Issue by magali-thuaire** [SymfonyCasts/reset-password-bundle#221]
Hi!
I try to test the parameter "enable_garbage_collection" but it doesn't work for me.

In the method removeExpiredResetPasswordRequests of the **ResetPasswordRequestRepositoryTrait**, why does :

```
$time = new \DateTimeImmutable('-1 week')
```
Thanks a lot for your work!

**Comment by Tofandel** [comment]
Well it only deletes token expired more than a week ago, why? Dunno. Does seem like a sensible default but could be configurable

**Comment by magali-thuaire** [comment]
You are right! It was surprised me because the documentation says :  
```
Enable or disable the Reset Password Cleaner which handles expired reset password requests that may have been left in persistence
```

And I didn't understand why the **expired tokens** were not deleted.
So, yes not a bug but maybe a parameter would be nice.

**Comment by jrushlow** [comment]
The actual removal of the expired tokens in done in "user-land" via the usage of the `ResetPasswordRequestRepositoryTrait`

https://github.com/SymfonyCasts/reset-password-bundle/blob/1cb844641b649c27e699701953d12c8ccf6706a0/src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php#L73

The default is to allow expired passwords to sit in persistence for 1 week. See https://github.com/SymfonyCasts/reset-password-bundle/pull/103 for the history behind why we default to 1 week.

I was sitting here like ya, lets add a config parameter so we can make this configurable.. But unfortunately its not that straight forward. Instead, I think a better solution is to just override the `ResetPasswordRequestRepositoryTrait::removeExpiredResetPasswordRequests()` within you application. Change the `-1 week` value in the datetime constructor to whatever suites your needs. https://github.com/SymfonyCasts/reset-password-bundle/blob/1cb844641b649c27e699701953d12c8ccf6706a0/src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php#L75

E.g. removing the `-1 week` argument all together would remove anything that expired as of "today". Or you change it to `-1 days`, etc..
