### ISSUE TITLE
Flash messages are not show in in .../check_email.html.twig

### ISSUE THREAD

**Issue by alister** [SymfonyCasts/reset-password-bundle#223]
In the default `ResetPasswordController::reset()` action, there is a (commented-out) suggestion for how to *'tell the user why a reset email was not sent'*.

I uncommented it (wrapped in a `$this->isGranted('ROLE_SUPPORT') {...`), but no flash messages are shown - because the `check_email.html.twig` template does not check & display the flashes.

If you think adding the flashes to the template is a useful addition, I'd be happy to make a PR. It may also be useful to create a local `.../reset_password/layout.html.twig` base-file to remove the further duplication of the flashes-block that already has 2 copies.

**Comment by bocharsky-bw** [comment]
Thank you for this suggestion!

It seems it was already implemented, see https://github.com/SymfonyCasts/reset-password-bundle/blob/85e59bb6dcf7904f4febc6a2cad1337ab2e1ba3c/tests/Fixtures/App/templates/reset_password/request.html.twig#L6-L8

So the flash message now works out of the box.

Cheers!
