### ISSUE TITLE
ResetPasswordRemoveExpiredCommand deprecation with Symgony 6.1

### ISSUE THREAD

**Issue by laurentmuller** [SymfonyCasts/reset-password-bundle#224]
I'm using this bundle with Symfony 6.1. 

A deprecation is raised for the `ResetPasswordRemoveExpiredCommand `command:

`The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final. You should not override it in "SymfonyCasts\Bundle\ResetPassword\Command\ResetPasswordRemoveExpiredCommand".
`

The default name must replaced by the `AsCommand` attribute.

See : [Registering the Command](https://symfony.com/doc/current/console.html#registering-the-command)

**Comment by chindit** [comment]
This has been fixed by #234 ( `AsCommand` will need to wait when PHP7 compatibility is dropped)

**Comment by bocharsky-bw** [comment]
Thank you for fixing it! Closing in favor of https://github.com/SymfonyCasts/reset-password-bundle/pull/234
