### ISSUE TITLE
Is this feature work with API Platform?

### ISSUE THREAD

**Issue by wokalove** [SymfonyCasts/reset-password-bundle#228]
Before installing this bundle I want to ensure if it has chance to work with non monolitic application.  I mean - I use API Platform on server side and client side is in external app written in pure Vue (not in twig as most tutorial shows).

**Comment by jontjs** [comment]
Duplicate of https://github.com/SymfonyCasts/reset-password-bundle/issues/128

**Comment by bocharsky-bw** [comment]
Good catch! Please, read the related thread in #128 first or feel free to ask additional comments there if you can't find an answer to your question
