### ISSUE TITLE
Symfony 6.1 not capable

### ISSUE THREAD

**Issue by Flower7C3** [SymfonyCasts/reset-password-bundle#244]
This bundle is mentioned in Symfony 6.1 documentation https://symfony.com/doc/6.1/security/passwords.html#reset-password but I am unable to install it, due the composer.json dependencies.

**Comment by jrushlow** [comment]
Are you using PHP 8.1? If so, you'll need to be on at least 8.1.10. See https://github.com/SymfonyCasts/reset-password-bundle/releases/tag/v1.15.0
