### ISSUE TITLE
Requires default_uri to be defined

### ISSUE THREAD

**Issue by akincer** [SymfonyCasts/reset-password-bundle#249]
This might confuse some folks that are getting localhost as the root of the generated URI due to url() in twig prepending localhost without having default_uri defined in routing.yaml.

**Comment by weaverryan** [comment]
I don't think we can require `default_uri` in this bundle, as it comes from another bundle. However, this is definitely an easy place to mess up, so it could definitely be mentioned in the README - like if you're getting `localhost` URLs on production, you should set this.

**Comment by akincer** [comment]
Right. Should have been more explicit - for production and a note in the
README was exactly what I had in mind.

**Comment by weaverryan** [comment]
PR warmly welcomed for this :)

**Comment by akincer** [comment]
Created. If the wording needs changed just let me know.

**Comment by bocharsky-bw** [comment]
Just for reference: #250
