### ISSUE TITLE
`"php": ">=8.1 <8.1.10"` in the `composer.json` prevents installation.

### ISSUE THREAD

**Issue by omatamix** [SymfonyCasts/reset-password-bundle#251]
That line provides errors during installation.

![Capture](https://user-images.githubusercontent.com/47761650/200184607-2b033f0a-c82a-466e-b6bf-ded705c71902.PNG)

**Comment by omatamix** [comment]
I don't understand why we need `"php": ">=8.1 <8.1.10"` in the conflicts part on the composer json.

**Comment by omatamix** [comment]
If the difference time bug is an issue, there is a workaround. Just look at https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Traits/Difference.php to see how Carbon does it.

**Comment by imajim** [comment]
#if you're using PHP v8.1.x we've added a composer conflict for PHP versions 8.1.0 through 8.1.9. This is due to a time bug that was introduced in PHP 8.1.0 but has been fixed in PHP 8.1.10.
https://github.com/SymfonyCasts/reset-password-bundle/releases/tag/v1.15.0

**Comment by bocharsky-bw** [comment]
Good catch @imajim ! Thanks for sharing the link to the release, it explains in detail why it was made so. Please, upgrade your PHP version to the minimum required to be able to safely use this bundle on it.

Cheers!

**Comment by sebheitzmann** [comment]
The azure pipeline run with php8.1.2 I Can't update it.

**Comment by mhitza** [comment]
I'm seeing the same issues with GitHub actions, it's on the same 8.1.2 PHP version

https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#php
