### ISSUE TITLE
Deprecation Message

### ISSUE THREAD

**Issue by On5-Repos** [SymfonyCasts/reset-password-bundle#252]
Method "Symfony\Component\Console\Command\Command::execute()" might add "int" as a native return type declaration in the future. Do the same in child class "EasyCorp\Bundle\EasyDeployBundle\Command\DeployCommand" now to avoid errors or add an explicit @return annotation to suppress this message.

Solution: Define Return Response on Method.

 **5.4.15 - Symfony version
 7.4.32  - PHP version
"symfonycasts/reset-password-bundle": "^1.16"**

It might cause issues during upgrade to Symfony 6.1

**Comment by jrushlow** [comment]
Howdy! I think you might have the wrong repo for your issue. The only command we have in `ResetPasswordBundle` is the `RemoveExpiredCommand` which already has the return type for `execute()` https://github.com/SymfonyCasts/reset-password-bundle/blob/1aaf7b11db793dbf594e7ec9c6fb880572a264d9/src/Command/ResetPasswordRemoveExpiredCommand.php#L43

Based on the message you've provided, it looks like this issue belongs in `easycorp/easy-deploy-bundle` https://github.com/EasyCorp/easy-deploy-bundle

That bundle is not used in `reset-password-bundle`

**Comment by On5-Repos** [comment]
sorry I should read more carefully apologies.

**Comment by jrushlow** [comment]
No worries at all - you'd be surprised how many time I've done that myself..
