### ISSUE TITLE
Cannot find the entity manager for class "App\Entity\ResetPasswordRequest" 

### ISSUE THREAD

**Issue by NCJavaCode** [SymfonyCasts/reset-password-bundle#256]
Hello, everybody.

When I use make:reset-password command system asks you two questions:
******************************************************************************************************************************
Let's make a password reset feature!
====================================

 Implementing reset password for App\Entity\User

- ResetPasswordController -
---------------------------

 A named route is used for redirecting after a successful reset. Even a route that does not exist yet can be used here.

 What route should users be redirected to after their password has been successfully reset? [app_home]:
 >

- Email -
---------

 These are used to generate the email code. Don't worry, you can change them in the code later!

 What email address will be used to send reset confirmations? e.g. mailer@your-domain.com:
 > xxxxxxxxx

 What "name" should be associated with that email address? e.g. "Acme Mail Bot":
 > xxxxxx

 created: src/Controller/ResetPasswordController.php
 created: src/Entity/ResetPasswordRequest.php

In DoctrineHelper.php line 91:

  Cannot find the entity manager for class "App\Entity\ResetPasswordRequest"  

make:reset-password
******************************************************************************************************************************
It's all!
What happen?

**Comment by spetters** [comment]
@NCJavaCode Might be the same issue as #247

**Comment by NCJavaCode** [comment]
@spetters Thank you.
