### ISSUE TITLE
Request: Allow to pass lifetime parameter in generateResetToken function on v1.14.1 version

### ISSUE THREAD

**Issue by DocBraaa** [SymfonyCasts/reset-password-bundle#266]
Hello,
I'm using symfony 4.4 version for a project. I've got a business requirement that guide me to create two different reset request with two different lifetime.

Like in latest version, can you add the possibility of pass the resetRequestLifetime parameter in generateResetToken function ?

Thank's

**Comment by bocharsky-bw** [comment]
Even if you're going to help by creating a PR for this feature, I'm not sure how we can technically do this in the current repository structure. We have all the tags pointing to the `main` branch of this repo, there are no different branches that we could switch and easily add changes. Does anybody know a good strategy to do this for the specific tag in the past?

**Comment by weaverryan** [comment]
We can always create a `1.14` branch off of the 1.14.0 tag, then commit to that. But apart from a security bug, I'm not inclined to do this, sorry :/. I know convincing owners/managers can be difficult sometimes, but 4.4 is receiving security fixes only - and only for a few more months https://symfony.com/releases/4.4
