### ISSUE TITLE
Cannot find the entity manager for class "App\Entity\ResetPasswordRequest"

### ISSUE THREAD

**Issue by astronati** [SymfonyCasts/reset-password-bundle#270]
After run `bin/console make:reset-password` and answering some questions I get following error:

`Cannot find the entity manager for class "App\Entity\ResetPasswordRequest"`

**Comment by bocharsky-bw** [comment]
Do you have a few entity managers configured in your project? Did you try to clear the cache, Is the error still the same? 

Btw, could you dobule check the `ResetPasswordRequest` entity, the properties inside should be declared with PHP attributes. Do you also use PHP attributes for your other entities? Or use annotations? You can't use both, so you would need to sync it.

**Comment by astronati** [comment]
Hi @bocharsky-bw,


- I've many repositories already configured.
- Cache cleared many times
- The codebase is based on attributes only, no annotations.

The entity follows:

```
<?php

namespace App\Entity;

use App\Repository\ResetPasswordRequestRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ResetPasswordRequestRepository::class)]
class ResetPasswordRequest
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }
}
```

**Comment by bocharsky-bw** [comment]
Yes, the bundle is supposed your entities are following the default src/Entity/ dir. So, I think you just need to move the new entity in the proper dir and fix namespaces everywhere. Actually, the Maker bundles is supposed to generate entities in the default src/Entity/ too. So, if you're not using a standard path - you need to do some extra work after files are generated.

Thanks for sharing your solution with others! Can we close this issue now?

**Comment by astronati** [comment]
Yes, even if I would suggest to use the path set in the configuration.

Thanks.

**Comment by bocharsky-bw** [comment]
Unfortunately, we just follow the logic of `make:entity` command - that command also does not allow you to set up a different folder (mostly for simplicity reasons I suppose). So the issue is not directly related to this repo. But I'm happy to hear you found a workaround on it

**Comment by astronati** [comment]
Thanks @bocharsky-bw ! ;)
