### ISSUE TITLE
Error 500 when open url from Gmail or 365 web client

### ISSUE THREAD

**Issue by saturit** [SymfonyCasts/reset-password-bundle#273]
I generate a password reset to the @gmail.com email, clicking on the link in the web client, symfony gives me a 500 error. Gmail is probably redirecting it weirdly and this bundle doesn’t like it. Same problem with 365. 

Redirect URL example: 

`https://www.google.com/url?q=https://domain/reset-hesla/reset/rIhoqNYlhS0PRI4TpHnby11P6l2clkG4vgtDnssh&source=gmail&ust=1698306363945000&usg=AOvVaw1FcA7L49YDAoHdwN05C12H`

ENV = prod

![image](https://github.com/SymfonyCasts/reset-password-bundle/assets/109578484/747ef792-b4f9-4740-b691-6879ca6a2421)

**Comment by bocharsky-bw** [comment]
Hm, if it gives you a 500 error - that's probably not the one related to the screenshot you sent. On the screenshot it should be 404 not found error I suppose. Please, double-check your logs to see what exactly 500 error you get. I hope that helps!

**Comment by saturit** [comment]
Hi @bocharsky-bw, 
in "PROD" env gives an error 500, ib "DEV" env gives error 400.  And yes, this package apparently does not work properly on different environments.

**Comment by weaverryan** [comment]
Hmm. As Victor mentioned, if you're getting a 500 error, it's not from the line in the screenshot. That line would trigger a 404 error in production as well.

So, first, for that 404, I would add some debug code to see what's going on. The flow should be:

A) User clicks a link that has a token as a query parameter
B) This controller grabs that, saves it to the session, then redirects to the same page without the token query parameter (there is a security reason why this is done).
C) The same controller reads that token from the session.

At some point, something is going wrong.

For the 500 on production, I'm not sure which part of the code is causing that (as I mentioned, it can't be the `createNotFoundException()` line, which always causes a 404 error). I would try to track down the actual error.

Cheers!
