### ISSUE TITLE
Flash message  in request.html.twig

### ISSUE THREAD

**Issue by alexz707** [SymfonyCasts/reset-password-bundle#285]
Hello :)
I've just searched how a flash message could be triggered to be displayed in the request.html.twig.
I could not find any reason why there should be a message displayed. Is this flash message template really necessary in request.html.twig ?
I tried to use a empty input or an invalid email like only % but I could trigger it and I could see in the code.

Can maybe someone tell me if I'm wrong or not ?
Thanks!

**Comment by alexz707** [comment]
sorry, just found it in the uncommented section, it is used when email sending has an error.
so maybe the flash messenger should be also commented out somehow in the template?

**Comment by jrushlow** [comment]
Howdy @alexz707 

I think the spot that you noticed this was in https://github.com/symfony/maker-bundle/blob/bbb7949ae048363df7c8439abeddef8befd155ce/src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php#L134 This message _is_ commented out for the reason stated in the comment. 

But a flash message is also added to the response when validation fails: https://github.com/symfony/maker-bundle/blob/bbb7949ae048363df7c8439abeddef8befd155ce/src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php#L79

You can test this out by going to `/reset/im-a-bad-token`, which should ultimately cause `ResetPasswordHelper::validateTokenAndFetchUser($token)` to throw a `ResetPasswordExceptionInterface` instance which we catch - then set a flash message before returning a redirect.

I hope this helps... Thanks!
