### ISSUE TITLE
Prevent export neon files

### ISSUE THREAD

**Issue by laurentmuller** [SymfonyCasts/reset-password-bundle#337]
The `.gitattributes` file can be updated to exclude the **.neon** files.

It's simple matter to add the following line:

```
.neon export-ignore
```

**Comment by bocharsky-bw** [comment]
Changes are good and simple, feel free to create a PR without issue about it, but let's order the list like it's done in https://github.com/SymfonyCasts/verify-email-bundle/pull/200 :)
