### ISSUE TITLE
require symfony mailer in composer

### ISSUE THREAD

**Issue by jrushlow** [SymfonyCasts/reset-password-bundle#49]
Bundle uses Symfony's Mailer component to send emails

- [ ] require symfony/mailer in composer.json
- [ ] reference in docs
- [ ] if ! exists `mailer_dsn` in .env - maker should create it
- [x] add maker text reminder to set correct `MAILER_DSN`

**Comment by weaverryan** [comment]
THIS bundle doesn't do anything with Mailer. We WILL need to make it a "dependency" inside the Maker command for sure, however.

**Comment by jrushlow** [comment]
I remember us talking about this before, issue is a leftover.
