### ISSUE TITLE
handle old / expired reset requests left in persistence

### ISSUE THREAD

**Issue by jrushlow** [SymfonyCasts/reset-password-bundle#8]
implement some sort of garbage collection default with option to disable. provide public methods to manually remove single/batch requests

**Comment by kbond** [comment]
Laravel has a command that you can schedule as a cron job to do this. Do you think we need something different?

**Comment by jrushlow** [comment]
@weaverryan and I talked a little bit about this. The first iteration of “garbage collection” will probably fall some where’s along those lines and be enable automatic enabled out of the box. There will be an option to disable that functionality while providing some form of helper to allow a custom implementation. 

I’ve a few code snippets that outline my thinking, but nothing that’s PR-able yet. I need to get everything else in order first, then take a look at the best course of action there after..
