### ISSUE TITLE
[BETA] composer installs non-essential files

### ISSUE THREAD

**Issue by jrushlow** [SymfonyCasts/reset-password-bundle#80]
when installing the bundle using `composer require symfonycasts/reset-password-bundle`, composer also installs dev related files/folders i.e. `tests/`.

This is not a big deal, but those files are not needed in a production env. Or a dev env outside of the actual development on the bundle. A `.gitattributes` file may be the solution to ignore said files. Thoughts?

**Comment by kbond** [comment]
+1 for `.gitattributes`.
