### ISSUE TITLE
Add Symfony 4.4 to test matrix

### ISSUE THREAD

**Issue by kbond** [SymfonyCasts/reset-password-bundle#82]
Since this bundle supports Symfony 4.4, should it be added to the test matrix? Or maybe just `--prefer-lowest`

**Comment by jrushlow** [comment]
Good catch. Thinking off the cuff, I'd say probably have a CI workflow for 4.4 and one for 5.x. It would allow for a clear, "Hey i'm broke over here in 4.x but 5.x passed.." `--prefer-lowest` isn't a bad idea either. 

I'll have to play around with it some to figure out which is easiest to maintain yet clear and concise. I'm still working on caching without a lock file as time allows and have a few ideas. This would play into the caching as well.

**Comment by kbond** [comment]
For some reference, here is the config for a bundle I have been working on that does this: https://github.com/kbond/schedule-bundle/blob/master/.github/workflows/tests.yml

Also, does the current setup actually run on the different PHP versions? I thought you had to add and configure the https://github.com/shivammathur/setup-php action. I can't see anything in the action logs that shows what PHP version it is running on.

**Comment by jrushlow** [comment]
Thanks for that, I'll definitely have a look at that!

> Also, does the current setup actually run on the different PHP versions?

Yes, when you define the php versions in the build [strategy](https://github.com/SymfonyCasts/reset-password-bundle/blob/239266e8ba6b513c053c86ac51feee9adc4e075c/.github/workflows/ci.yml#L8) it runs the tests concurrently across 7. 2,3,&4. When you look at the logs, you're only seeing the long for one build. Looking at the [actions tab](https://github.com/SymfonyCasts/reset-password-bundle/actions/runs/65907250) will show you all of the builds that the CI ran. 

This is what I'd like to be able to do with the symfony versions. Have it run across multiple builds concurrently to keep the overall CI time down in the 1 - 2 min range as we have now. 

I took a look at the `shivammathur/setup-php` action when actions for came to light and was pretty impressed with it. But it's more of a "shortcut" to what you can do with actions without it. (No disrespect to that action intended) Personally, I prefer to have "complete control" over what is happening without relying on a separate package to run the tests if that makes sense. That's not to say that action wouldn't prove useful in a more complicated CI test suite.
