### ISSUE TITLE
symfony/config throws deprecation in functional / integration tests in CI

### ISSUE THREAD

**Issue by jrushlow** [SymfonyCasts/reset-password-bundle#85]
`Since symfony/config 5.1: The signature of method "Symfony\Component\Config\Definition\Builder\NodeDefinition::setDeprecated()" requires 3 arguments: "string $package, string $version, string $message", not defining them is deprecated.`

Functional Test: `16x in ResetPasswordRequestRepositoryTest::setUp from SymfonyCasts\Bundle\ResetPassword\Tests\FunctionalTests\Persistence`

Integration Test: `2x in ResetPasswordInterfaceAutowireTest::testResetPasswordInterfaceIsAutowiredByContainer from SymfonyCasts\Bundle\ResetPassword\Tests\IntegrationTests`

**Comment by jrushlow** [comment]
This deprecation is indirectly triggered by the `DoctrineBundle`, see https://github.com/doctrine/DoctrineBundle/pull/1153 and was introduced by the `Symfony/Config` package. see https://github.com/symfony/symfony/pull/35871

**Comment by kbond** [comment]
This doc could be useful to help with this: https://symfony.com/doc/master/components/phpunit_bridge.html#making-tests-fail

**Comment by weaverryan** [comment]
I think we can close this now?

**Comment by jrushlow** [comment]
yup, fixed in PR #87
