### ISSUE TITLE
Maker command not work

### ISSUE THREAD

**Issue by azribilel** [SymfonyCasts/reset-password-bundle#91]
**./bin/console make:reset-pass**
The maker is not defined in two beta versions ?

**Comment by jrushlow** [comment]
Hi! I am working on the `make:reset-password` command as we speak. We released the beta version more or less for internal testing / development of the reset password command... 

While I cannot give a firm time/date as to when `make:reset-password` will be available, feel free to monitor the progress over in the [maker bundle repository](https://github.com/symfony/maker-bundle/pull/567)

**Comment by azribilel** [comment]
Hi @weaverryan 
i can use the bundle without the command ?
or i should wait ?

**Comment by jrushlow** [comment]
By all means yes. But, while the code base is pretty solid, there is still the possibility of breaking changes between now and the initial release.

The `make:reset-password` command essential does all of the grunt work laid out in the manual setup guide. It will also demonstrate how we intended the bundle to be used with an application.

I would strongly advise against using the bundle in a real production environment until we release v1.0. If you’re working on an app now in dev, by all means give the bundle a try and feedback is appreciated.

**Comment by azribilel** [comment]
Okay, I will give a try and thanks for the fast reply

**Comment by jrushlow** [comment]
@azribilel checkout [v1.0.0](https://github.com/SymfonyCasts/reset-password-bundle/releases) and `make:reset-password` is available in [v1.15](https://github.com/symfony/maker-bundle/releases) of the maker bundle!

Enjoy!
