### ISSUE TITLE
Typo `hasUserHisThrottling` (his instead of hit)

### ISSUE THREAD

**Issue by cjhaas** [SymfonyCasts/reset-password-bundle#98]
I'm pretty sure the method `hasUserHisThrottling()`  is really supposed to be `hasUserHitThrottling()`, right?
https://github.com/SymfonyCasts/reset-password-bundle/blob/262db21e1c5aea7c5ae5573e42aecf41c53fe33a/src/ResetPasswordHelper.php#L161

**Comment by jrushlow** [comment]
Yup, you're correct. Thanks for catching that.
